pyzaak_api_proto/frontend/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', views.signup, name='signup'),
    path('accounts/profile/', views.profile, name='profile'),
    # path('accounts/profile/edit', views.edit_profile, name='edit_profile')
]

pyzaak_api_proto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('pyzaak_api_proto.api.urls')),
    path('', RedirectView.as_view(url='api/', permanent=True))
]

pyzaak_api_proto/api/models.py
from django.db import models
from django.contrib.auth.models import User, Group
from django.db.models.signals import post_save
from django.dispatch import receiver


# Create your models here.
class Profile(models.Model):
    RANK_CHOICES = (
            (1, 'Mark'),
            (2, 'Novice'),
            (3, 'Hustler'),
            (4, 'Sharp'),
            (5, 'Force User')
        )

    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        primary_key=True
        )
    total_xp = models.IntegerField(default=0)
    rank = models.IntegerField(choices=RANK_CHOICES, default=0)
    games_played = models.IntegerField(default=0)
    games_won = models.IntegerField(default=0)
    location = models.CharField(max_length=30, blank=True)
    joined = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(blank=True, upload_to='images/')


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


class SideDeck(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        primary_key=True,
        related_name='side_deck'
        )
    plus_1 = models.IntegerField(default=1)
    minus_1 = models.IntegerField(default=1)
    bival_1 = models.IntegerField(default=0)
    plus_2 = models.IntegerField(default=1)
    minus_2 = models.IntegerField(default=1)
    bival_2 = models.IntegerField(default=0)
    plus_3 = models.IntegerField(default=0)
    minus_3 = models.IntegerField(default=0)
    bival_3 = models.IntegerField(default=0)
    plus_4 = models.IntegerField(default=0)
    minus_4 = models.IntegerField(default=0)
    bival_4 = models.IntegerField(default=0)
    plus_5 = models.IntegerField(default=0)
    minus_5 = models.IntegerField(default=0)
    bival_5 = models.IntegerField(default=0)
    plus_6 = models.IntegerField(default=0)
    minus_6 = models.IntegerField(default=0)
    bival_6 = models.IntegerField(default=0)


@receiver(post_save, sender=User)
def create_user_side_deck(sender, instance, created, **kwargs):
    if created:
        SideDeck.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_side_deck(sender, instance, **kwargs):
    instance.side_deck.save()


@receiver(post_save, sender=User)
def post_save_user_signal_handler(sender, instance, created, **kwargs):
    if created:
        group = Group.objects.get(name='EndUser')
        instance.groups.add(group)
        instance.save()


class Game(models.Model):
    finished_at = models.DateTimeField(auto_now_add=True)
    user_1 = models.ForeignKey(
            User,
            on_delete='PROTECT',
            related_name='user_1',
            )
    user_2 = models.ForeignKey(
        User,
        on_delete='PROTECT',
        related_name='user_2'
        )
    user_1_rank = models.IntegerField(choices=Profile.RANK_CHOICES)
    user_2_rank = models.IntegerField(choices=Profile.RANK_CHOICES)
    winner = models.ForeignKey(
        User,
        on_delete='PROTECT',
        related_name='winner')
    user_1_xp_delta = models.IntegerField()
    user_2_xp_delta = models.IntegerField()

pyzaak_api_proto/frontend/models.py
from django.db import models
from django.contrib.auth.models import User


class BlogPost(models.Model):
    title = models.CharField(max_length=100)
    body = models.TextField()
    created_by = models.ForeignKey(User, on_delete="PROTECT")
    date_added = models.DateTimeField(auto_now_add=True)

pyzaak_api_proto/frontend/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(
        max_length=30,
        required=False,
        help_text='Optional.'
        )
    last_name = forms.CharField(
        max_length=30,
        required=False,
        help_text='Optional.'
        )
    email = forms.EmailField(
        max_length=254,
        help_text='Required. Inform a valid email address.'
        )

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
            )


# class EditProfileForm(forms.ModelForm):
#     location = forms.CharField(required=False)
#     image = forms.ImageField(required=False)

#     class Meta:
#         model = User
#         fields = ('username', 'email')

pyzaak_api_proto/frontend/views.py
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect
# from django.conf import settings
# from django.core.files.storage import FileSystemStorage
from django.contrib.auth.decorators import login_required
from django.core import serializers

from api.models import Profile, SideDeck, Game
from .models import BlogPost
from .forms import SignUpForm


def home(request):
    games = Game.objects.all().order_by('-finished_at')
    try:
        post = BlogPost.objects.latest('date_added')
    except DoesNotExist:
        post = {title: 'No Posts',
                body: 'Add a post!',
                created_by: '',
                date_added: None}
    return render(request, 'frontend/home.html', {'games': games, 'post': post})


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('home')
    else:
        form = SignUpForm()
    return render(request, 'frontend/signup.html', {'form': form})


@login_required
def profile(request):
    user = request.user
    profile = Profile.objects.get(user=user)
    deck = serializers.serialize("python",
                                 [SideDeck.objects.get(user=user)])[0]
    context = {'user': user,
               'profile': profile,
               'deck': deck}
    return render(request, 'frontend/profile.html', context)


# @login_required
# def edit_profile(request):
#     user = request.user
#     profile = Profile.objects.get(user=user)
#     if request.method == 'POST':
#         if request.FILES['image']:
#             image = request.FILES['imge']
#             fs = FileSystemStorage()
#             filename = fs.save(myfile.name, myfile)
#             uploaded_file_url = fs.url(filename)
#         profile.image = form.cleaned_data.pop('image')
#         profile.location = form.cleaned_data.pop('location')
#         profile.save()
#         form.save()
#         return redirect('profile')

#     deck = serializers.serialize("python",
#                                  [SideDeck.objects.get(user=user)])[0]
#     context = {'user': user,
#                'profile': profile}
#     return render(request, 'frontend/edit_profile.html', context)

pyzaak_api_proto/frontend/templates/frontend/edit_profile.html
{% extends 'base.html' %}

{% block content %}
<br />
<form method="POST" action="/accounts/profile/edit" enctype="multipart/form-data">
{% csrf_token %}
<div class="row">
    <div class="col-2">
        {% if profile.image %}
        <img src="{{ profile.image.url }}" class="img-fluid" />
        {% endif %}
        <label class="btn btn-default btn-file">
        Change image<input type="file" name="image" style="display: none;" />
        </label>
    </div>
    <div class="col-10">
        <h1><input type="text" name="username" value="{{ user.username }}" /></h1>
        <input class="btn btn-primary" type="submit" value="Save Changes" />
    </div>
</div>
<br />
<div class="row">
    <div class="col-2">
    </div>
    <div class="col">
        <p>Email:</p>
        <p>Location:</p>
    </div>
    <div class="col">
        <p><input type="text" name="email" value="{{ user.email }}" /></p>
        <p><input type="text" name="location" value="{{ profile.location}}" /></p>
    </div>
</div>
</form>
<br />
<div class="row">
</div>


{% endblock %}

pyzaak_api_proto/frontend/templates/frontend/home.html
{% extends 'base.html' %}

{% block content %}
<div class="row pt-4">
    <div class="col-10">
        <h1>Pyzaak Prototype</h1>
    </div>
</div>
<div class="row pt-4">
    <div class="col-2">
    </div>
    <div class="col-8">
        <h3>{{ post.title }}</h3>
        <h5>By {{post.created_by}}, {{ post.date_added|date:'n/j/Y' }}</h5>
        <p>{{ post.body }}</p>
    </div>
</div>
<div class="row pt-4">
    <div class="col-10 pb-2">
        <h4>Recent Games</h4>
    </div>
    <div class="col-10 pb-6">
        <table class="table table-dark">
            <thead>
                <tr>
                    <th scope="col"></th>
                    <th scope="col">Player 1</th>
                    <th scope="col">P1 XP</th>
                    <th scope="col">Player 2</th>
                    <th scope="col">P2 XP</th>
                </tr>
            </thead>
            <tbody>
                {% for game in games %}
                <tr>
                    <td>
                        {{ game.finished_at|date:'P n/j/Y' }}
                    </td>
                    <td>
                        {{ game.user_1 }} ({{ game.get_user_1_rank_display }})
                        }
                        {% if game.winner == game.user_1 %}
                        <p style="color:#66ff99">Winner!</p>
                        {% endif %}
                    </td>
                    <td>
                        {% if game.user_1_xp_delta > 0 %}
                        +
                        {% endif %}
                        {{ game.user_1_xp_delta }}
                    </td>
                    <td>
                        {{ game.user_2 }} ({{ game.get_user_2_rank_display }})
                        {% if game.winner == game.user_2 %}
                        <p style="color:#66ff99">Winner!</p>
                        {% endif %}
                    </td>
                    <td>
                        {% if game.user_2_xp_delta > 0 %}
                        +
                        {% endif %}
                        {{ game.user_2_xp_delta }}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

pyzaak_api_proto/frontend/templates/frontend/profile.html
{% extends 'base.html' %}

{% block content %}
<br />
<div class="row pt-3">
    <div class="col-2">
        {% if profile.image %}
        <img src="{{ profile.image.url }}" class="img-fluid" />
        {% endif %}
    </div>
    <div class="col-10">
        <h1>{{ user.username }}</h1>
        {# <a href="{% url 'edit_profile' %}">Edit profile</a> #}
    </div>
</div>

<div class="row pt-2">
    <div class="col-2">
    </div>
    <div class="col">
        <p>Joined:</p>
        <p>Games Played:</p>
        <p>Games Won:</p>
        <p>Rank:</p>
        <p>Location:</p>
    </div>
    <div class="col">
        <p>{{ profile.joined|date:'M j, Y' }}</p>
        <p>{{ profile.games_played }}</p>
        <p>{{ profile.games_won }}</p>
        <p>{{ profile.get_rank_display }}</p>
        <p>{{ profile.location|default:"Unavailable" }}</p>
    </div>
</div>
<div class="table-responsive pt-3">
  <table class="table table-sm table-bordered">
    <caption>{{ user.username }}'s Side Deck</caption>
    <thead>
      <tr>
        <th>+1</th>
        <th>-1</th>
        <th>+/-1</th>
        <th>+2</th>
        <th>-2</th>
        <th>+/-2</th>
        <th>+3</th>
        <th>-3</th>
        <th>+/-3</th>
        <th>+4</th>
        <th>-4</th>
        <th>+/-4</th>
        <th>+5</th>
        <th>-5</th>
        <th>+/-5</th>
        <th>+6</th>
        <th>-6</th>
        <th>+/-6</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        {% for field, value in deck.fields.items %}
        <td>{{ value }}</td>
        {% endfor %}
      </tr>
    </tbody>
  </table>
</div>


{% endblock %}

pyzaak_api_proto/frontend/templates/frontend/signup.html
{% extends 'base.html' %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}